export const REGISTER_USER_PROFESSOR = "REGISTER_USER_PROFESSOR";

export const LOGIN_USER_PROFESSOR = "LOGIN_USER_PROFESSOR";
export const CURRENT_USER_PROFESSOR = "CURRENT_USER_PROFESSOR";
export const LOAD_USER_PROFESSOR = "LOAD_USER_PROFESSOR";
export const FAIL_USER_PROFESSOR = "FAIL_USER_PROFESSOR";
export const LOGOUT_USER_PROFESSOR = "LOGOUT_USER_PROFESSOR";