export const REGISTER_USER = "REGISTER_USER_STUDENT";

export const LOGIN_USER = "LOGIN_USER_STUDENT";
export const CURRENT_USER = "CURRENT_USER_STUDENT";
export const LOAD_USER = "LOAD_USER_STUDENT";
export const FAIL_USER = "FAIL_USER_STUDENT";
export const LOGOUT_USER = "LOGOUT_USER_STUDENT";